# ansible-playbook -vvv --user=ubuntu  mo_prod.yml -i ./ec2.py  -c ssh
# ansible-playbook -vvv --user=root mo_prod.yml -c ssh
- hosts: movide
  vars_files:
    - "{{ secure_dir }}/vars/movide_prod_vars.yml"
    - "{{ secure_dir }}/users/users.yml"
  roles:
    - mo
  sudo: True