from settings import *
import json

with open(ENV_ROOT / "env.json") as env_file:
    ENV_TOKENS = json.load(env_file)

with open(ENV_ROOT / "auth.json") as auth_file:
    AUTH_TOKENS = json.load(auth_file)

DEBUG = False

DATABASES = AUTH_TOKENS.get('DATABASES', DATABASES)
allowed_hosts = ENV_TOKENS.get('ALLOWED_HOSTS')
if allowed_hosts is not None:
    ALLOWED_HOSTS += allowed_hosts

#Allauth
ACCOUNT_EMAIL_VERIFICATION = ENV_TOKENS.get('ACCOUNT_EMAIL_VERIFICATION', 'mandatory')

GOOGLE_ANALYTICS_KEY = ENV_TOKENS.get('GOOGLE_ANALYTICS_KEY')
ACCOUNT_EMAIL_REQUIRED = ENV_TOKENS.get('ACCOUNT_EMAIL_REQUIRED', True)

AWS_ACCESS_KEY_ID = AUTH_TOKENS.get('AWS_ACCESS_KEY_ID', AWS_ACCESS_KEY_ID)
AWS_SECRET_ACCESS_KEY = AUTH_TOKENS.get('AWS_SECRET_ACCESS_KEY', AWS_SECRET_ACCESS_KEY)

SEND_EMAIL_EVERY = ENV_TOKENS.get('SEND_EMAIL_EVERY', SEND_EMAIL_EVERY)
SCRAPE_DATA_EVERY = ENV_TOKENS.get('SCRAPE_DATA_EVERY', SCRAPE_DATA_EVERY)
MINIMUM_ARTICLE_LENGTH = ENV_TOKENS.get('MINIMUM_ARTICLE_LENGTH', MINIMUM_ARTICLE_LENGTH)

ARTICLES_TO_REGENERATE = ENV_TOKENS.get('ARTICLES_TO_REGENERATE', ARTICLES_TO_REGENERATE)
ARTICLES_TO_GENERATE = ENV_TOKENS.get('ARTICLES_TO_GENERATE', ARTICLES_TO_GENERATE)
ARTICLES_TO_SHOW = ENV_TOKENS.get('ARTICLES_TO_SHOW', ARTICLES_TO_SHOW)
TRENDING_CACHE_TIME = ENV_TOKENS.get('TRENDING_CACHE_TIME', 60 * 60)

MINIMUM_TAGGED = ENV_TOKENS.get('MINIMUM_TAGGED', 200)

FACEBOOK_APP_ID = AUTH_TOKENS.get('FACEBOOK_APP_ID', FACEBOOK_APP_ID)
FACEBOOK_TOKEN = AUTH_TOKENS.get('FACEBOOK_TOKEN', FACEBOOK_TOKEN)

REDDIT_USER_AGENT = ENV_TOKENS.get('REDDIT_USER_AGENT', REDDIT_USER_AGENT)

TWITTER_ACCESS_TOKEN = AUTH_TOKENS.get('TWITTER_ACCESS_TOKEN', TWITTER_ACCESS_TOKEN)
TWITTER_SECRET_ACCESS_TOKEN = AUTH_TOKENS.get('TWITTER_SECRET_ACCESS_TOKEN', TWITTER_SECRET_ACCESS_TOKEN)

TWITTER_APP_KEY = AUTH_TOKENS.get('TWITTER_APP_KEY', TWITTER_APP_KEY)
TWITTER_SECRET_APP_KEY = AUTH_TOKENS.get('TWITTER_SECRET_APP_KEY', TWITTER_SECRET_APP_KEY)

TWITTER_AUTH_APP_KEY = AUTH_TOKENS.get('TWITTER_AUTH_APP_KEY', TWITTER_AUTH_APP_KEY)
TWITTER_AUTH_SECRET_APP_KEY = AUTH_TOKENS.get('TWITTER_AUTH_SECRET_APP_KEY', TWITTER_AUTH_SECRET_APP_KEY)

SCORE_CONTENT = True

SECRET_KEY = AUTH_TOKENS.get('SECRET_KEY', SECRET_KEY)