from settings import *
import json

with open(ENV_ROOT / "env.json") as env_file:
    ENV_TOKENS = json.load(env_file)

with open(ENV_ROOT / "auth.json") as auth_file:
    AUTH_TOKENS = json.load(auth_file)

DEBUG = False

DATABASES = AUTH_TOKENS.get('DATABASES', DATABASES)
allowed_hosts = ENV_TOKENS.get('ALLOWED_HOSTS')
if allowed_hosts is not None:
    ALLOWED_HOSTS += allowed_hosts

# Allauth.
ACCOUNT_EMAIL_VERIFICATION = ENV_TOKENS.get('ACCOUNT_EMAIL_VERIFICATION', 'optional')

UPDATE_GRADING_QUEUE_EVERY = ENV_TOKENS.get('UPDATE_GRADING_QUEUE_EVERY', 15 * 60)

GOOGLE_ANALYTICS_KEY = ENV_TOKENS.get('GOOGLE_ANALYTICS_KEY')
ACCOUNT_EMAIL_REQUIRED = ENV_TOKENS.get('ACCOUNT_EMAIL_REQUIRED', True)
SOCIALACCOUNT_EMAIL_REQUIRED = ENV_TOKENS.get('SOCIALACCOUNT_EMAIL_REQUIRED', True)

AWS_ACCESS_KEY_ID = AUTH_TOKENS.get('AWS_ACCESS_KEY_ID', AWS_ACCESS_KEY_ID)
AWS_SECRET_ACCESS_KEY = AUTH_TOKENS.get('AWS_SECRET_ACCESS_KEY', AWS_SECRET_ACCESS_KEY)

SECRET_KEY = AUTH_TOKENS.get('SECRET_KEY', SECRET_KEY)